SEARCH_ANALYTICS_DIMENSIONS = ["query"]
SEARCH_ANALYTICS_PAGE_DIMENSIONS = ["page"]
SEARCH_ANALYTICS_ROW_LIMIT = 1_000
COUNTRY_FILTER_EXPRESSION = "CAN"
COUNTRY_FILE_PREFIX = "canada"


def country_file_prefix(country: str | None) -> str:
    if country == COUNTRY_FILTER_EXPRESSION:
        return f"{COUNTRY_FILE_PREFIX}_"
    return ""


GSC_API_KEY_ENV_VAR = "GSC_API_KEY"
