SEARCH_ANALYTICS_DIMENSIONS = ["query"]
SEARCH_ANALYTICS_PAGE_DIMENSIONS = ["page"]
SEARCH_ANALYTICS_ROW_LIMIT = 1_000

GSC_API_KEY_ENV_VAR = "GSC_API_KEY"
GSC_BEARER_TOKEN_ENV_VAR = "GSC_BEARER_TOKEN"
